add native parquet writer blog
prestodb/prestodb.github.io pull request #141
Opened 2021-05-20 03:13 UTC by qqibrow

@zhenxiao @highker Please review. Thanks!

2021-05-20 04:33 UTC, zhenxiao approved these changes
thank you, @qqibrow 
looks good to me. 2 minor issues

2021-05-20 04:33 UTC, zhenxiao commented on website/blog/2021-05-19-native-parquet-writer-for-presto.md
> +With the wide deployment of Presto in more and more companies, Presto is used not only for queries, but also for data ingestion and ETL jobs. There are the needs to improve Presto’s file writer perfo
remove . before 2X

2021-05-20 04:33 UTC, zhenxiao commented on website/blog/2021-05-19-native-parquet-writer-for-presto.md
> +Presto has performance testing HiveFileFormatBenchmark to test reader and writer performance. The test creates a list of pages containing millions of rows, writes them to a temp file using either nat
with GZIP compression, continue with the previous line?

2021-05-20 19:08 UTC, aweisberg commented on website/blog/2021-05-19-native-parquet-writer-for-presto.md
> +
```suggestion

<!-- truncate -->

```

2021-05-20 19:20 UTC, aweisberg requested changes
Please don't forget to squash after accepting any changes and clean up the commit message.

2021-05-31 20:32 UTC, qqibrow commented on website/blog/2021-05-19-native-parquet-writer-for-presto.md
> +Presto was calling the Hive record writer to consume each individual record and write value bytes to Parquet pages.
changed to `Then Presto would call`

2021-05-31 20:34 UTC, qqibrow commented
@aweisberg Thanks for the review! fixed all comments. Please take a look. Thanks!

2021-06-07 23:42 UTC, qqibrow commented
@aweisberg Could you take a look? thanks!

2021-06-29 01:18 UTC, aweisberg commented on website/blog/2021-05-19-native-parquet-writer-for-presto.md
> +If you have any questions, feel free to ask in the presto slack channel.
It looks like you didn't take this one? Did it not make a working link?

2021-06-29 01:24 UTC, aweisberg requested changes
Two minor nits, plus the slack channel mention should link to the slack channel. Thanks!

2021-06-29 01:24 UTC, aweisberg commented on website/blog/2021-05-19-native-parquet-writer-for-presto.md
> +This old approach first iterates each columnar block in a page and reconstructing every single record.
```suggestion
This old approach first iterates each columnar block in a page and reconstructs every single record.
```

2021-06-29 01:24 UTC, aweisberg commented on website/blog/2021-05-19-native-parquet-writer-for-presto.md
> +Presto has vectorized execution for in-memory columnar data, and Parquet is a columnar file format. The old Parquet writer was adding unnecessary overhead to convert Presto’s columnar in-memory data
```suggestion
Presto has vectorized execution for in-memory columnar data, and Parquet is a columnar file format. The old Parquet writer was adding unnecessary overhead to convert Presto’s columnar in-memory data into row based records, and then doing one more conversion to write row based records to Parquet’s columnar on disk file format. The unnecessary data transformation adds significant performance overhead, especially when complex data types are involved such as nested structs.
```

2021-06-30 13:18 UTC, aweisberg approved these changes
Awesome, thank you. @zhenxiao  can you merge?

2021-06-30 16:15 UTC, zhenxiao approved these changes
looks good. thank you, @aweisberg

2021-06-30 16:15 UTC, merged