Add blog post for disaggregated coordinator
prestodb/prestodb.github.io pull request #162
Opened 2022-02-17 06:47 UTC by swapsmagic

2022-02-17 21:22 UTC, highker reviewed
Haven't looked into details but do have some high-level comments on the figures:
- The fonts seem to be inconsistent. Usually, it would be good to have figure fonts to be 1 size smaller than the text font size. (Or at least easy to read).
- Some of the fonts are too small from a browser.
- The font size in the boxes is a bit disproportional from the box sizes. The text is too small and boxes are too big. (Check our Presto paper https://research.facebook.com/publications/presto-sql-on-everything/ to see the font size vs box size).

Regarding the content itself, Tim and Ariel could be better reviewers than me given they are closer to the work + native English speakers lol

2022-02-18 17:02 UTC, aweisberg requested changes
Content looks quite good. Only have minor tweaks. And some push back on including documentation in the blog. The blog is for advertising :-)

2022-02-18 17:02 UTC, aweisberg commented on website/blog/2022-02-17-disggregated-coordinator.md
> +The following flags can help one tune the cluster’s resource groups to the desired consistency:
The flags should go into the Presto docs and be linked to from here :-) 
There shouldn't be anything to elaborate on that isn't already in the docs. Really if the blog post never existed the docs should be sufficient to explain what people need to know to enable and operate this feature (including why they would).

2022-02-18 17:02 UTC, aweisberg commented on website/blog/2022-02-17-disggregated-coordinator.md
> +## Configuration
This should also be in the docs. Basically I am just pushing back on putting documentation in blog posts. It leaves the docs incomplete and goes out of date over time.

2022-03-15 03:56 UTC, rohanpednekar commented
@swapsmagic Thanks for your contribution, this is really great content. Do you think we can target the end of this month to publish this article?

2022-04-11 07:01 UTC, swapsmagic commented
> @swapsmagic Thanks for your contribution, this is really great content. Do you think we can target the end of this month to publish this article?

Waiting for this PR https://github.com/prestodb/presto/pull/17597 to get merged before i can update this and refer to the official doc in the blog. Once that's done it's good to merge.

2022-04-14 14:39 UTC, aweisberg commented on website/blog/2022-02-17-disggregated-coordinator.md
> +## Configuration
Can we only link to the docs for the configuration? This is the thing that is most likely to go out of date and be incorrect so it's better not to duplicate it.

2022-04-15 14:40 UTC, aweisberg approved these changes
LGTM, thank you!

2022-04-15 18:41 UTC, merged